# golangci-lint configuration file
# Updated to follow best practices and prepare for V2 transition
version: v1.60.1

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - copyloopvar  # replaces exportloopref in newer versions
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goerr113
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomnd
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - staticcheck
    - stylecheck
    - tenv
    - testableexamples
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
    - wrapcheck

  disable:
    - exportloopref  # deprecated, replaced by copyloopvar
    - scopelint      # deprecated
    - structcheck    # deprecated
    - varcheck       # deprecated
    - maligned       # deprecated
    - interfacer     # deprecated
    - golint         # deprecated
    - wsl            # deprecated

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
